# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'dgdb'

pod 'React', :path => '../node_modules/react-native', subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation',
  'RCTActionSheet',
  'RCTBlob',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTPushNotification',
  'RCTSettings',
  'RCTTest',
  'RCTVibration',
  'RCTLinkingIOS'
]

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# pod 'react-native-config', :path => '../node_modules/react-native-config'

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'react-native-webview', :path => '../node_modules/react-native-webview'

# Third party deps podspec link
  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'